version: '3.7'

services:
  database:
    container_name: fooddb
    image: mysql:8.0
    restart: always
    ports:
      - "33061:3306"
    volumes:
      - golang-docker-data:/var/lib/mysql
    networks:
      - foodnt
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=food
      - MYSQL_DATABASE=FoodRecommendation
      - MYSQL_PASSWORD=Ahmad@13741112
  
volumes:
  golang-docker-data:

networks:
  foodnt:
