FROM golang:1.18

ENV GO111MODULE=on
ENV PORT 5000
ARG UID=1000
ARG GID=1000

RUN groupadd -r --gid $GID user && useradd -r --uid $UID -g user user

WORKDIR /app

ADD . /app

RUN go mod tidy
RUN go mod verify

RUN go build -o /food

EXPOSE $PORT

CMD [ "bash", "./devops/entrypointProd.sh", "/food", "serve", "docker-config-template.yml" ]