FROM golang:1.18 as builder

ENV GO111MODULE=on

WORKDIR /app

ADD . ./

RUN go mod tidy
RUN go mod verify

RUN CGO_ENABLED=0 GOOS=linux go build -o food

FROM alpine:3.14

# install bash
RUN apk update && apk add bash
# For Alpine:3.3+
# RUN apk add --no-cache bash

ENV PORT 5000

WORKDIR /app

COPY --from=builder /app /app

EXPOSE $PORT

CMD [ "bash", "./devops/entrypointProd.sh", "/app/food", "serve", "docker-config-template.yml" ]